[package]
name = "atom"
version = "0.2.0-beta.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.7.0"
strum = "0.22.0"
wyhash2 = "0.2.1"
indexmap = "1.7.0"
test-case = "1.2.0"
rustyline = "9.0.0"
clap = "3.0.0-beta.5"
lazy_static = "1.4.0"
strum_macros = "0.21.1"
snmalloc-rs = { version = "0.2.28", optional = true }


[features]
default = ["snmalloc"]
snmalloc = ["snmalloc-rs"]

[profile.release]
debug = true
