[package]
name = "atom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.7.0"
wyhash2 = "0.2.1"
indexmap = "1.7.0"
smallvec = "1.6.1"
snmalloc-rs = "0.2"
test-case = "1.1.0"
rustyline = "8.2.0"
clap = "3.0.0-beta.2"
