[package]
name = "atom"
version = "0.3.0"
edition = "2021"

[profile.release]
panic = "abort"
debug = true

[dependencies]
logos = "0.12.0"
anyhow = "1.0.57"
temp-dir = "0.1.11"
inkwell = "0.1.0-beta.4"
clap = { version = "3.1.18", features = ["derive"] }