[package]
name = "atom"
version = "0.2.0-beta.0"
edition = "2021"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "^0.7"
strum = "^0.22"
wyhash2 = "^0.2"
indexmap = "^1"
test-case = "^1"
rustyline = "^9"
enumflags2 = "^0.7"
clap = "3.0.0-beta.5"
lazy_static = "^1"
strum_macros = "^0.21"
snmalloc-rs = { version = "^0.2", optional = true }

[features]
default = ["snmalloc"]
snmalloc = ["snmalloc-rs"]