<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>atom</string>
        </array>
        <key>foldingStartMarker</key>
        <string>(?x)
            /\*\*(?!\*)
            |^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
        </string>
        <key>foldingStopMarker</key>
        <string>(?&lt;!\*)\*\*/|^\s*\}</string>
        <key>name</key>
        <string>atom</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(if|for|in|extern|is|module|import|else|class|mixin|extends|unsafe|raise|continue|interface|break|return|when|raise)\b</string>
                <key>name</key>
                <string>keyword.control.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\bmut\b</string>
                <key>name</key>
                <string>storage.modifier.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\blet\b</string>
                <key>name</key>
                <string>keyword.other.let.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\bpub\b</string>
                <key>name</key>
                <string>storage.modifier.visibility.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?:(import))\b</string>
                <key>name</key>
                <string>keyword.control.import.$1.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(true|false|Int|Bool|Float|Array|Map|String|Byte|Char|Range)\b</string>
                <key>name</key>
                <string>constant.language.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b([1-9]+[0-9]*|0)</string>
                <key>name</key>
                <string>constant.numeric.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(this)\b</string>
                <key>name</key>
                <string>variable.language.atom</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>f"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string_placeholder</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string_placeholder</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>'</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.single.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string_placeholder</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>match</key>
                <string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=</string>
                <key>name</key>
                <string>keyword.operator.comparison.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\+|\-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~|&lt;\=&gt;\\.\.\.</string>
                <key>name</key>
                <string>keyword.operator.arithmetic.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\=</string>
                <key>name</key>
                <string>keyword.operator.assignment.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>:</string>
                <key>name</key>
                <string>keyword.operator.others.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\[|\]</string>
                <key>name</key>
                <string>keyword.operator.domain.atom</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>(?=[A-Za-z_][A-Za-z0-9_]*(?:\.[a-zA-Z_][a-zA-Z_0-9]*)*\s*\()</string>
                <key>end</key>
                <string>(\))</string>
                <key>name</key>
                <string>meta.function-call.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(?=[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*\s*\()</string>
                        <key>end</key>
                        <string>(?=\s*\()</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#builtin_functions</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\()</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.arguments.begin.atom</string>
                            </dict>
                        </dict>
                        <key>contentName</key>
                        <string>meta.function-call.arguments.atom</string>
                        <key>end</key>
                        <string>(?=\))</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>\b(fn)\s*(?:\s+([a-zA-Z_][a-zA-Z0-9_]*(?:([\.:])[a-zA-Z_][a-zA-Z0-9_]*)?)\s*)?(\()</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.atom</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.atom</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.separator.parameter.atom</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.parameters.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.parameters.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.function.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>[a-zA-Z_][a-zA-Z0-9_]*</string>
                        <key>name</key>
                        <string>variable.parameter.function.atom</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>,</string>
                        <key>name</key>
                        <string>punctuation.separator.arguments.atom</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.dictionary.begin.atom</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>meta.empty-dictionary.atom</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.dictionary.end.atom</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\{)(\s*(\}))</string>
                <key>name</key>
                <string>meta.structure.dictionary.atom</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>(\{)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.dictionary.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(\})</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.dictionary.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.dictionary.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(?&lt;=\{|\,|^)\s*(?![\},])</string>
                        <key>contentName</key>
                        <string>meta.structure.dictionary.key.atom</string>
                        <key>end</key>
                        <string>\s*(?:(?=\})|(\=>))</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.separator.valuepair.dictionary.atom</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(?&lt;=\=>|^)\s*</string>
                        <key>contentName</key>
                        <string>meta.structure.dictionary.value.atom</string>
                        <key>end</key>
                        <string>\s*(?:(?=\})|(,))</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.separator.dictionary.atom</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>builtin_functions</key>
            <dict>
                <key>match</key>
                <string>(?x)\b(println|some)\b</string>
                <key>name</key>
                <string>support.function.builtin.atom</string>
            </dict>
            <key>comments</key>
            <dict>
                <key>begin</key>
                <string>(^[ \t]+)?(?=#)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.whitespace.comment.leading.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(?!\G)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>#</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.atom</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>\n</string>
                        <key>name</key>
                        <string>comment.line.number-sign.atom</string>
                    </dict>
                </array>
            </dict>
            <key>entity_name_function</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#illegal_names</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#generic_names</string>
                    </dict>
                </array>
            </dict>
            <key>generic_names</key>
            <dict>
                <key>match</key>
                <string>[A-Za-z_][A-Za-z0-9_]*</string>
            </dict>
            <key>illegal_names</key>
            <dict>
                <key>match</key>
                <string>
                    \b(fn|for|in|is|if|else|break|return|mut)\b
                </string>
                <key>name</key>
                <string>invalid.illegal.name.atom</string>
            </dict>
            <key>string_escaped_char</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>
                            \\(\\|[abefnprtv'"?]|[0-3]\d{0,2}|[4-7]\d?|x[a-fA-F0-9]{0,2}|u[a-fA-F0-9]{0,4}|U[a-fA-F0-9]{0,8})
                        </string>
                        <key>name</key>
                        <string>constant.character.escape.c</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\\.</string>
                        <key>name</key>
                        <string>invalid.illegal.unknown-escape.c</string>
                    </dict>
                </array>
            </dict>
            <key>string_placeholder</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(?x)%
                            (\d+\$)? # field (argument #)
                            [#0\- +']* # flags
                            [,;:_]? # separator character (AltiVec)
                            ((-?\d+)|\*(-?\d+\$)?)? # minimum field width
                            (\.((-?\d+)|\*(-?\d+\$)?)?)? # precision
                            (hh|h|ll|l|j|t|z|q|L|vh|vl|v|hv|hl)? # length modifier
                            [diouxXDOUeEfFgGaACcSspn%] # conversion type
                        </string>
                        <key>name</key>
                        <string>constant.other.placeholder.c</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>scopeName</key>
        <string>source.atom</string>
        <key>uuid</key>
        <string>1721A2F6-7268-4A22-98F9-BCD688D199B4</string>
    </dict>
</plist>
