<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>atom</string>
        </array>
        <key>foldingStartMarker</key>
        <string>(?x)
            /\*\*(?!\*)
            |^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
        </string>
        <key>foldingStopMarker</key>
        <string>(?&lt;!\*)\*\*/|^\s*\}</string>
        <key>name</key>
        <string>Atom</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(if|for|module|import|else|class|unsafe|raise|continue|break|return|when|raise)\b</string>
                <key>name</key>
                <string>keyword.control.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(let|mut|pub)\b</string>
                <key>name</key>
                <string>storage.modifier.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(true|false)\b</string>
                <key>name</key>
                <string>constant.language.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>
                    \b((0(b|B)[0-1]([0-1]|_)*)|(0(o|O)[0-7]([0-7]|_)*)|(0(x|X)((([0-9a-fA-F]([0-9a-fA-F]|_)*\.?([0-9a-fA-F]([0-9a-fA-F]|_)*)?)|(\.[0-9a-fA-F]([0-9a-fA-F]|_)*))((p|P)(\+|-)?[0-9]([0-9]|_)*)?))|(0(x|X)[0-9a-fA-F]([0-9a-fA-F]|_)*)|((([0-9]([0-9]|_)*\.?([0-9]([0-9]|_)*)?)|(\.[0-9]([0-9]|_)*))((e|E)(\+|-)?[0-9]([0-9]|_)*)?))\b
                </string>
                <key>name</key>
                <string>constant.numeric.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(this)\b</string>
                <key>name</key>
                <string>variable.language.atom</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.chapel</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string_placeholder</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>'</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.atom</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.single.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string_placeholder</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>match</key>
                <string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=</string>
                <key>name</key>
                <string>keyword.operator.comparison.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\+\=|-\=|\*\=|/\=|//\=|%\=|&amp;\=|\|\=|\^\=|&gt;&gt;\=|&lt;&lt;\=|\*\*\=</string>
                <key>name</key>
                <string>keyword.operator.assignment.augmented.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\+|\-|\*|\*\*|/|//|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~|&lt;\=&gt;\\.\.\.</string>
                <key>name</key>
                <string>keyword.operator.arithmetic.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\=</string>
                <key>name</key>
                <string>keyword.operator.assignment.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>:</string>
                <key>name</key>
                <string>keyword.operator.others.atom</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\[|\]</string>
                <key>name</key>
                <string>keyword.operator.domain.atom</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>^\s*((pub )?fn)\s+(?=[A-Za-z_][A-Za-z0-9_]*)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.atom</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(\()|\s*($\n?|#.*$\n?)</string>
                <key>name</key>
                <string>meta.function.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
                        <key>contentName</key>
                        <string>entity.name.function.atom</string>
                        <key>end</key>
                        <string>(?![A-Za-z0-9_])</string>
                    </dict>
                    <dict>
                        <key>contentName</key>
                        <string>keyword.control.atom</string>
                        <key>match</key>
                        <string>fn</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\()</string>
                        <key>contentName</key>
                        <string>meta.function.parameters.atom</string>
                        <key>end</key>
                        <string>(?=\)).*\{</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>captures</key>
                                <dict>
                                    <key>1</key>
                                    <dict>
                                        <key>name</key>
                                        <string>variable.parameter.function.atom</string>
                                    </dict>
                                </dict>
                                <key>match</key>
                                <string>\b([a-zA-Z_][a-zA-Z_0-9]*)</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>(?=[A-Za-z_][A-Za-z0-9_]*(?:\.[a-zA-Z_][a-zA-Z_0-9]*)*\s*\()</string>
                <key>end</key>
                <string>(\))</string>
                <key>name</key>
                <string>meta.function-call.atom</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(?=[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*\s*\()</string>
                        <key>end</key>
                        <string>(?=\s*\()</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#builtin_functions</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\()</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.arguments.begin.atom</string>
                            </dict>
                        </dict>
                        <key>contentName</key>
                        <string>meta.function-call.arguments.atom</string>
                        <key>end</key>
                        <string>(?=\))</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>$self</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>builtin_functions</key>
            <dict>
                <key>match</key>
                <string>(?x)\b(
                    println

                    )\b
                </string>
                <key>name</key>
                <string>support.function.builtin.atom</string>
            </dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>//</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.c</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>$\n?</string>
                        <key>name</key>
                        <string>comment.line.double-slash.c++</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>match</key>
                                <string>(?&gt;\\\s*\n)</string>
                                <key>name</key>
                                <string>punctuation.separator.continuation.c++</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>entity_name_function</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#illegal_names</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#generic_names</string>
                    </dict>
                </array>
            </dict>
            <key>generic_names</key>
            <dict>
                <key>match</key>
                <string>[A-Za-z_][A-Za-z0-9_]*</string>
            </dict>
            <key>illegal_names</key>
            <dict>
                <key>match</key>
                <string>
                    \b(fn|for|if|else|break|return|mut)\b
                </string>
                <key>name</key>
                <string>invalid.illegal.name.chapel</string>
            </dict>
            <key>string_escaped_char</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>
                            \\(\\|[abefnprtv'"?]|[0-3]\d{0,2}|[4-7]\d?|x[a-fA-F0-9]{0,2}|u[a-fA-F0-9]{0,4}|U[a-fA-F0-9]{0,8})
                        </string>
                        <key>name</key>
                        <string>constant.character.escape.c</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\\.</string>
                        <key>name</key>
                        <string>invalid.illegal.unknown-escape.c</string>
                    </dict>
                </array>
            </dict>
            <key>string_placeholder</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(?x)%
                            (\d+\$)? # field (argument #)
                            [#0\- +']* # flags
                            [,;:_]? # separator character (AltiVec)
                            ((-?\d+)|\*(-?\d+\$)?)? # minimum field width
                            (\.((-?\d+)|\*(-?\d+\$)?)?)? # precision
                            (hh|h|ll|l|j|t|z|q|L|vh|vl|v|hv|hl)? # length modifier
                            [diouxXDOUeEfFgGaACcSspn%] # conversion type
                        </string>
                        <key>name</key>
                        <string>constant.other.placeholder.c</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>scopeName</key>
        <string>source.atom</string>
        <key>uuid</key>
        <string>1721A2F6-7268-4A22-98F9-BCD688D199B4</string>
    </dict>
</plist>
