[package]
name = "atom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.7.0"
strum = "0.22.0"
wyhash2 = "0.2.1"
indexmap = "1.7.0"
test-case = "1.2.0"
rustyline = "9.0.0"
clap = "3.0.0-beta.4"
lazy_static = "1.4.0"
atom-ir = { path = "../atom-ir" }
atom-runtime = { path = "../atom-runtime" }
atom-macros = { path = "../atom-macros" }
snmalloc-rs = { version = "0.2.28", optional = true }

[features]
default = ["snmalloc"]
snmalloc = ["snmalloc-rs"]
